services:
  - type: web
    name: youtube-summarizer
    env: python
    buildCommand: pip install --no-cache-dir --upgrade -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
